server:
  port: 9991

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: books-list
        uri: lb://books-list
        predicates:
        - Path=/books-list/**
        filters:
        - RewritePath=/books-list/(?<path>.*), /$\{path}

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
